version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      day: monday
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      day: monday
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: docker
    directory: /
    schedule:
      day: monday
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
